# Generated by Django 4.0.5 on 2022-07-11 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_category_options_alter_color_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ratingpeople',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
