# Generated by Django 4.0.5 on 2022-07-11 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_product_ratingpeople'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reviews',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
