# Generated by Django 4.0.5 on 2022-07-11 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_product_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='reviews',
        ),
    ]
