# Generated by Django 4.0.5 on 2022-07-12 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_remove_product_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='oldprice',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
